### PR TITLE
more translations and corrects

### PR DESCRIPTION
**Pull request by vanja-san**
more and more and more

### CODE REVIEW

**Comment by vanja-san** [comment]
@Akke It seems to me or I'm wasting my time, the translation is not updated at all in the game. 🥲

**Comment by Akke** [comment]
> @Akke It seems to me or I'm wasting my time, the translation is not updated at all in the game. 🥲

We update once a week every Friday. Except for the ocassional bug fixes.

**Comment by vanja-san** [comment]
@Akke Okay, you can do a merge with that too. It's hard to find untranslated text, it seems most of it has already been translated.

**Comment by Akke** [comment]
This is currently in conflict due to the latest update. You can see in the patch notes what's different. Mostly Centaur, the skill books, battle mage's arsenal etc.

**Pull request closed without merging**
