### PR TITLE
Translation of some lines

### PR DESCRIPTION
**Pull request by vanja-san**
New corrects and a new translation

### CODE REVIEW

**Comment by vanja-san** [comment]
@Akke Can I remove everything that is commented out?

**Comment by Akke** [comment]
Sure thing!

**Comment by vanja-san** [comment]
@Akke Can I do it this way (...modifier_player_buffs... - RUNES)? Shortened it a bit:
ru : `+95% к сопротивлению эффектам.<br>+40% ко всему получаемому урона.`
original : `Increases Status Resistance by 95% but increases damage taken from all sources by 40%.`

and is it possible to say not "taken from all sources", but "from all taken damage"?

**Comment by Akke** [comment]
> @Akke Can I do it this way (...modifier_player_buffs... - RUNES)? Shortened it a bit:
> ru : `+95% к сопротивлению эффектам.<br>+40% ко всему получаемому урона.`
> original : `Increases Status Resistance by 95% but increases damage taken from all sources by 40%.`
> 
> and is it possible to say not "taken from all sources", but "all taken damage"?

Yeah whatever sounds the best.

**Comment by vanja-san** [comment]
@Akke While I'm thinking, I need to take a break. You can check and merge. All untranslated strings will be translated later!😪

**Comment by Akke** [comment]
> @Akke While I'm thinking, I need to take a break. You can check and merge. All untranslated strings will be translated later!😪

Awesome work! Thank you!

**Pull request merged**
